name: 'Decrypt and Mask Secrets'
description: 'Decrypts a zip and masks the JSON contents as env vars'

inputs:
  zip_password:
    description: 'Password for the Zip'
    required: true

  zip_path:
    description: 'Path to the encrypted zip'
    required: false
    default: 'secrets.zip'

runs:
  using: 'composite'

  steps:
    - name: install python deps
      shell: powershell
      run: |
        python -m pip install pyzipper

    - name: Decrypt and Mask
      shell: powershell
      run: |
        python -c "import pyzipper,json,os; z=pyzipper.AESZipFile('${{ inputs.zip_path }}'); z.setpassword('${{ inputs.zip_password }}'.encode()); f=z.open('secrets.json'); secrets=json.load(f); f.close(); z.close(); env=open(os.environ['GITHUB_ENV'],'a'); [ (print(f'::add-mask::{v}'), env.write(f'{k}={v}\n')) for k,v in secrets.items() if v ]; env.close(); print(f'Successfully masked {len(secrets)} secrets.')"
